package com.dhkim.common

enum class Region(val country: String, val code: String) {
    Korea("대한민국", "KR"),
    US("미국", "US"),
    Japan("일본", "JP"),
    Andorra("안도라", "AD"),
    UnitedArabEmirates("아랍에미리트 연합", "AE"),
    AntiguaAndBarbuda("앤티가 바부다", "AG"),
    Albania("알바니아", "AL"),
    Angola("앙골라", "AO"),
    Argentina("아르헨티나", "AR"),
    Austria("오스트리아", "AT"),
    Australia("호주", "AU"),
    Azerbaijan("아제르바이잔", "AZ"),
    BosniaAndHerzegovina("보스니아 헤르체고비나", "BA"),
    Barbados("바베이도스", "BB"),
    Belgium("벨기에", "BE"),
    BurkinaFaso("부르키나파소", "BF"),
    Bulgaria("불가리아", "BG"),
    Bahrain("바레인", "BH"),
    Bermuda("버뮤다", "BM"),
    Bolivia("볼리비아", "BO"),
    Brazil("브라질", "BR"),
    Bahamas("바하마", "BS"),
    Belarus("벨라루스", "BY"),
    Belize("벨리즈", "BZ"),
    Canada("캐나다", "CA"),
    Congo("콩고-킨샤사", "CD"),
    Switzerland("스위스", "CH"),
    CoteDIvoire("코트디부아르", "CI"),
    Chile("칠레", "CL"),
    Cameroon("카메룬", "CM"),
    Colombia("콜롬비아", "CO"),
    CostaRica("코스타리카", "CR"),
    Cuba("쿠바", "CU"),
    CapeVerde("까뽀베르데", "CV"),
    Cyprus("사이프러스", "CY"),
    CzechRepublic("체코", "CZ"),
    Germany("독일", "DE"),
    Denmark("덴마크", "DK"),
    DominicanRepublic("도미니카 공화국", "DO"),
    Algeria("알제리", "DZ"),
    Ecuador("에콰도르", "EC"),
    Estonia("에스토니아", "EE"),
    Egypt("이집트", "EG"),
    Spain("스페인", "ES"),
    Finland("핀란드", "FI"),
    Fiji("피지", "FJ"),
    France("프랑스", "FR"),
    UnitedKingdom("영국", "GB"),
    FrenchGuiana("프랑스령 기아나", "GF"),
    Ghana("가나", "GH"),
    Gibraltar("지브롤터", "GI"),
    Guadeloupe("과들루프", "GP"),
    EquatorialGuinea("적도 기니", "GQ"),
    Greece("그리스", "GR"),
    Guatemala("과테말라", "GT"),
    Guyana("가이아나", "GY"),
    HongKong("홍콩, 중국 특별행정구", "HK"),
    Honduras("온두라스", "HN"),
    Croatia("크로아티아", "HR"),
    Hungary("헝가리", "HU"),
    Indonesia("인도네시아", "ID"),
    Ireland("아일랜드", "IE"),
    Israel("이스라엘", "IL"),
    India("인도", "IN"),
    Iraq("이라크", "IQ"),
    Iceland("아이슬란드", "IS"),
    Italy("이탈리아", "IT"),
    Jamaica("자메이카", "JM"),
    Jordan("요르단", "JO"),
    Kenya("케냐", "KE"),
    Kuwait("쿠웨이트", "KW"),
    Lebanon("레바논", "LB"),
    SaintLucia("세인트루시아", "LC"),
    Liechtenstein("리히텐슈타인", "LI"),
    Lithuania("리투아니아", "LT"),
    Luxembourg("룩셈부르크", "LU"),
    Latvia("라트비아", "LV"),
    Libya("리비아", "LY"),
    Morocco("모로코", "MA"),
    Monaco("모나코", "MC"),
    Moldova("몰도바", "MD"),
    Montenegro("몬테네그로", "ME"),
    Madagascar("마다가스카르", "MG"),
    Macedonia("마케도니아", "MK"),
    Mali("말리", "ML"),
    Malta("몰타", "MT"),
    Mauritius("모리셔스", "MU"),
    Malawi("말라위", "MW"),
    Mexico("멕시코", "MX"),
    Malaysia("말레이시아", "MY"),
    Mozambique("모잠비크", "MZ"),
    Niger("니제르", "NE"),
    Nigeria("나이지리아", "NG"),
    Nicaragua("니카라과", "NI"),
    Netherlands("네덜란드", "NL"),
    Norway("노르웨이", "NO"),
    NewZealand("뉴질랜드", "NZ"),
    Oman("오만", "OM"),
    Panama("파나마", "PA"),
    Peru("페루", "PE"),
    FrenchPolynesia("프랑스령 폴리네시아", "PF"),
    PapuaNewGuinea("파푸아뉴기니", "PG"),
    Philippines("필리핀", "PH"),
    Pakistan("파키스탄", "PK"),
    Poland("폴란드", "PL"),
    Palestine("팔레스타인 지구", "PS"),
    Portugal("포르투갈", "PT"),
    Paraguay("파라과이", "PY"),
    Qatar("카타르", "QA"),
    Romania("루마니아", "RO"),
    Serbia("세르비아", "RS"),
    Russia("러시아", "RU"),
    SaudiArabia("사우디아라비아", "SA"),
    Seychelles("쉐이쉘", "SC"),
    Unknown("알 수 없음", "Unknown");

    companion object {
        fun seriesRegion(code: String): Region? = Region.entries.find { it.code == code }
    }
}